name: Kristina Crowley
favicon: null
layout_spectrum: 0.76039
typography_spectrum: 0.87799
title: A Little Bit of Everything
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b7b70'
    - '#fac369'
    - '#000000'
    - '#aec4c1'
    - '#256799'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
