name: Kristina Crowley
favicon: null
layout_spectrum: 0.92753
typography_spectrum: 0.52639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1eada'
    - '#cbc8bf'
    - '#adaea6'
    - '#39405d'
    - '#738089'
  brandStrength: 0.6178468624129891
  lightness: 0.9805561238899827
  saturation: 0.6875
  rhythmicContrast: 0.8876320710405707
purpose: []
