name: Kristina Crowley
favicon: null
layout_spectrum: 0.16895
typography_spectrum: 0.52639
title: A Little Bit of Everything
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b7b70'
    - '#fac369'
    - '#000000'
    - '#aec4c1'
    - '#256799'
  brandStrength: 0.6178468624129891
  lightness: 0.9805561238899827
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
