name: Kristina Crowley
favicon: null
layout_spectrum: 0.7180208065547049
typography_spectrum: 0.4445097013376653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6178468624129891
  lightness: 0.9805561238899827
  saturation: 0.6718538478016853
  rhythmicContrast: 0.8876320710405707
purpose: []
